[project]
name = 'certificate-challenge'
version = '0.0.1'
dependencies = [
  'fastapi==0.111.0',
  'playwright==1.43.0',
]

[project.optional-dependencies]
dev = [
    'rich==13.7.1',
    'isort==5.13.2',
    'blue==0.9.1',
]